name: Microfrontend automation - Container


on:
  # When this actions occurs
  push:
    # On specific branch 
    branch:
      # In summary: Run this workflow when a push is made to master 
      - master
    # When these paths are changed
    paths:
      # In summary: Run this workflow when changes are made in this directory
      - "packages/container/**"

defaults:
  run:
    working-directory: "packages/container"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build 
      - run: echo "build successfull!"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Invalidate AWS Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env: 
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/container/index.html"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://microfrontendapp/container --delete