name: Microfrontend Automation - Marketing



on:
  push:
    branch:
      master
    paths:
      "packages/marketing/*"

defaults:
  run:
    workingDirectory: "packages/marketing"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        run: actions@checkout@v2
      
      - name: Install packages
        run: npm install
      
      - name: Build repo
        run: npm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY}}
          aws-region: us-east-1
      

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://microfrontendapp/marketing --delete